### ISSUE TITLE
Consistent syntax errors

### ISSUE THREAD

**Issue by griff** [mwkuster/uritemplate-clj#3]
My URI templates are supplied by a user and so being able to syntax check them becomes important. But right now there isn't a consistent way of determining if a template is invalid. Different errors have very different results.

A good place to start would be to test with the negative-tests.json.

**Comment by mwkuster** [comment]
What categories of errors do you think would make sense? Further input or (of course) code to implement better error handling is very welcome

**Comment by mwkuster** [comment]
No feedback received
