### ISSUE TITLE
Reserved expansion operator pct-encodes colon, violating RFC

### ISSUE THREAD

**Issue by ryantate** [mwkuster/uritemplate-clj#8]
It looks like there is a bug in uritemplate-clj's handling of the plus ("+") variable expansion operator ("http://example.com{+foo}") also known as the reserved expansion operator.

According to the [RFC](https://tools.ietf.org/html/rfc6570#section-3.2.3), colons (":") should not be percent encoded when variables are expanded with "+".

This is shown most concisely when the RFC defines the example variable "base" in section 3.2...

```
base  := "http://example.com/home/"
```

...and then shows how this variable should be expanded with the plus ("+") expansion operator in section 3.2.3:

```
{+base}index          http://example.com/home/index
```

Fuller explanation: 3.2.3 defines the reserved expansion operator (plus, "+") as "identical to simple string expansion except that the substituted values may also contain pct-encoded triplets and characters in the reserved set." Section 1.5 classifies the colon as part of the reserved set (citing another RFC).

This is the behavior I'm seeing from uritemplate-clj 1.2.3:
```
(uritemplate-clj.core/uritemplate "{+base}index" {"base" "http://example.com/home/"})
"http%3A//example.com/home/index"
```

The slashes have correctly been left unencoded but the colon is percent encoded.

PS Thanks for the great library!

**Comment by ryantate** [comment]
In case anyone else encounters this problem before it is fixed, I am working around it like so (which indicates the fix should be pretty straightforward):

```
(in-ns 'uritemplate-clj.core)
(def ^String special-chars  (str special-chars ":"))

(in-ns 'your.original.namespace)
...
```

**Comment by mwkuster** [comment]
Thanks a lot, @ryantate , for spotting the issue and suggesting the fix!
